### ISSUE TITLE
Clipboard bug if you have text instead of an URL

### ISSUE THREAD

**Issue by Esoeth** [thetobby/Tmal#13]
There's currently an issue when you press mouse3 (Middlemouse) where the following would happen:

Leftclick -> CTRL+A
Ctrl +C
Open firefox with clipboard content

So if you have a sentence like "I like icecream" it will open up a 3 new tabs in firefox (1 tab per word).

Workaround: Swap off the clipboard setting in the .exe file.

Tobby got this on the todo list.

**Comment by thetobby** [comment]
Closed relevant duplicate issue #11 , this will be fixed in next release.

**Comment by thetobby** [comment]
Solved in v1.2
